/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jojoldu.blogcode.springboot.tips;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
